version: "3.4"


networks:
  custom-rasa-network:
    driver: bridge
    
services:      
  db:
    restart: always
    image: "bitnami/postgresql:${POSTGRESQL_VERSION}"
    networks:
      - custom-rasa-network
    expose:
      - "5432"
    environment:
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
    volumes:
      - ./db:/bitnami/postgresql

  rabbit:
    restart: always
    image: "bitnami/rabbitmq:${RABBITMQ_VERSION}"
    networks:
      - custom-rasa-network
    environment:
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    expose:
      - "5672"

  duckling:
    restart: always
    image: "rasa/duckling:${RASA_DUCKLING_VERSION}"
    networks:
      - custom-rasa-network
    expose:
      - "8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]

  redis:
    restart: always
    image: "bitnami/redis:${REDIS_VERSION}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    expose:
      - "6379"
